### ISSUE TITLE
Audio renderer error. Please restart your computer.

### ISSUE THREAD

**Issue by bahibzaf** [shibajee/realtek-uad-nahimic-mod#4]
![MaxthonSnap20200414001337](https://user-images.githubusercontent.com/61892903/79169678-f84c8000-7de4-11ea-80a1-6d2e6855bddd.png)

I get this error whenever i start or if i pause and resume a video in youtube. And videos won't play sometimes in other sites as well.

**Comment by shibajee** [comment]
This is a common problem in ASIO driver, search on google there r other solution but I think the problem can be fixed by below-
Press Windows key+R and type > mmsys.cpl
hit enter and double click ur playback device (speakers or headphones whatever u using now)
Go to advanced and in default format select 16 bit 44100 or 16 bit 48000 then apply ok.
I mean one of this format options could solve ur problem so u can try other formats, see which one solve ur problem. @bahibzaf
