### ISSUE TITLE
Najimic Cannot or Is not compatible

### ISSUE THREAD

**Issue by jan1030albz** [shibajee/realtek-uad-nahimic-mod#8]
I have Realtek Device hardware ID that ends with 282. pretty compatible but after following these instructions i still got error on nahimic only. It says that Nahimic cannot run or is not compatible.

**Comment by epman100** [comment]
**DO NOT INSTALL NAHIMIC 3 v1.4.4 APP FROM MS STORE!**

from [this post on Notebook review forums](http://forum.notebookreview.com/threads/nahimic-3-on-unsupported-systems.822763/page-85#post-11011110) - "WARNING: Nahimic 3 UWP has been updated from 1.4.2.0 to 1.4.4.0, This new version seems to completely break Nahimic 3 being used with the Driver Mod."

Disable MS store auto updates and downgrade Nahimic 3 app to either v1.4.1 or v1.4.2 (meaning uninstall v1.4.4 of the Nahimic 3 app and obtain an older version like 1.4.2 from [ASRock](https://download.asrock.com/Utility/Nahimic/Nahimic3(v200420).zip)).
Version 1.4.4 of Nahimic 3 app from MS store "**breaks**" Realtek UAD Nahimic modded drivers and is not compatible

**Comment by shibajee** [comment]
updated the driver, it will work now @jan1030albz

**Comment by epman100** [comment]
I think this issue needs to be re-opened

Microsoft Store has recently issued version **1.5.1** of the Nahimic 3 app which may produce the "not compatible" message on some older systems

so it needs another new modded driver update with newer Nahimic integration files

**Comment by shibajee** [comment]
Yes, the driver needs an update. I'll update it within 1 week. @epman100

**Comment by epman100** [comment]
thanks.  though the weird part is that [someone in ASRock forums](http://forum.asrock.com/forum_posts.asp?TID=16387&PN=3&title=nahimic-driver-outdated) used a really old Realtek driver version that works with the newest Nahimic 3 v1.5.1.0 app.

**Comment by epman100** [comment]
I ultimately found the problem why the version 1.5.x of the Nahimic3 app does not work or says "not compatible" with your latest modded driver, shibajee.

these new versions have a "Vendor ID" check routine and if those vendor registry ID entries do not exist, then they will fail to run and thus produce "not compatible" message.

need to add the following entries in the INF files in future releases of your modded driver:

%PKEY_VENDORNAME%,,%VENDORNAME%
PKEY_VENDORNAME	= "{3B454CDE-1938-473F-9DBF-5D6A56332FB5},0"
VENDORNAME = "MSI"
{note: the "VENDORNAME" string **cannot** be a blank one like "".  some valid strings for VENDORNAME are "ASRock", "Gigabyte", "Huawei" and "MSI" as they have current partnerships with Nahimic}

right below something like this entry in the INF files:
HKR,InterfaceSetting\SysCustomizedFx\EP\0,%PKEY_PRODUCTID%,,%PRODUCTID%
add this entry for example:
HKR,InterfaceSetting\SysCustomizedFx\EP\0,%PKEY_VENDORNAME%,,%VENDORNAME%


get a copy of [this guy's](http://forum.notebookreview.com/threads/nahimic-3-on-unsupported-systems.822763/page-112#post-11061180) latest modded Realtek uad nahimic MSI driver and look for the **AVoluteNH3Ext.inf** file and examine that file closely.  the "VENDORNAME" entries are there in that extension INF file.  with the new "VENDORNAME" entries added onto the INF files, newer Nahimic 3 app versions like 1.5.1.0, 1.5.2.0 & greater will work.  also don't forget to obtain the newest **NH3ProductSettings.cab** file as well from that other modded driver since MSI has been regularly getting updated AVoluteNH3Ext.inf & NH3ProductSettings.cab files from Nahimic.

**Comment by shibajee** [comment]
yeah, I figured it out during testing and already updated the driver to 9066 version. @epman100

**Comment by Yooooomi** [comment]
I'm still having the not compatible issue.
I remember realtek showing here but it doesn't anymore, does it have something to do with my issue ?
![image](https://user-images.githubusercontent.com/17204739/100770385-7e154e00-33fd-11eb-9892-3169bdc56b2b.png)

**Comment by epman100** [comment]
> 
> 
> yeah, I figured it out during testing and already updated the driver to 9066 version. @epman100

ah nuts!

did you also include the following in the **hdxrtsst.inf** file?

%PKEY_PRODUCTID_ISST%,,%PRODUCTID%
PKEY_PRODUCTID_ISST = "{9B8844FE-1650-40E5-A5EA-11B8C83821A1},12"
{I found those SST based entries in the AVoluteNH3Ext.inf file from certain Huawei/HONOR based Realtek UAD/DCH drivers that have Nahimic APO UWP integration}

I think those are needed for SST based Realtek HDA devices with HWIDs beginning with INTELAUDIO\FUNC_01&VEN_10EC

best to have both "%PKEY_PRODUCTID%,,%PRODUCTID% and %PKEY_PRODUCTID_ISST%,,%PRODUCTID% entries in the hdxrtsst.inf file so that Nahimic3 works on Intel SST based Realtek HD audio hardware

**Comment by epman100** [comment]
> 
> 
> I'm still having the not compatible issue.
> I remember realtek showing here but it doesn't anymore, does it have something to do with my issue ?
> ![image](https://user-images.githubusercontent.com/17204739/100770385-7e154e00-33fd-11eb-9892-3169bdc56b2b.png)

your issue might be different and maybe unrelated to the compatibility problem.

check the **Sound, video and game controllers** section of Device Manager, expand **that** section and check if **Realtek(R) Audio** is listed there.  if it's not there, then you either do not have a Realtek audio device or the Realtek hardware is disabled or broken

**Comment by Yooooomi** [comment]
Ok it's here, but nahimic does not work. The driver is the one installed by your package since it is not signed
![image](https://user-images.githubusercontent.com/17204739/100867972-3d6c1200-349b-11eb-91ae-689e31e15cf1.png)

**Comment by shibajee** [comment]
> Ok it's here, but nahimic does not work. The driver is the one installed by your package since it is not signed
> ![image](https://user-images.githubusercontent.com/17204739/100867972-3d6c1200-349b-11eb-91ae-689e31e15cf1.png)

ur system has nahimic mirroring service installed which messing with the driver, uninstall or remove it..afaik nahimic mirroring don't work with modded driver @Yooooomi

**Comment by shibajee** [comment]
Yeah, didn't include the string on SST inf. I usually follow the files from MSI driver, on MSI driver there is no "PKEY_PRODUCTID_ISST" string on inf but when I looked into the Asus SS3 driver there was. I don't have a device with INTELAUDIO to test so I guess I will just put both "PKEY_PRODUCTID and PKEY_PRODUCTID_ISST" on hdxrtsst.inf. @epman100

**Comment by epman100** [comment]
thanks.

perhaps maybe do a separate modded realtek nahimic driver that uses Nahimic APO4 SWC files (ex. NahimicAPO4.dll) instead of Nahimic APO3 files.  the Nahimic 3 v1.5x uwp app seems to work with either APO3 or APO4 set of integration files.  the Nahimic APO4 SWC files are used with certain 11th gen Intel & newer AMD Ryzen systems.

**Comment by shibajee** [comment]
> thanks.
> 
> perhaps maybe do a separate modded realtek nahimic driver that uses Nahimic APO4 SWC files (ex. NahimicAPO4.dll) instead of Nahimic APO3 files. the Nahimic 3 v1.5x uwp app seems to work with either APO3 or APO4 set of integration files. the Nahimic APO4 SWC files are used with certain 11th gen Intel & newer AMD Ryzen systems.

yap, APO4 works but again with app v1.5.2...v1.5.4 doesn't work anymore either with APO3 or APO4..I think this is it, this is the last version of app that will ever work. On next apo library (.dll) update app v1.5.2 won't work too, so we r kinda stuck with APO3 v3.1.0.0 and APO4 v4.1.5.0 with app v1.5.2. Every fun things have an end I guess. @epman100

**Comment by epman100** [comment]
a v1.5.7 release of the Nahimic uwp app is recently available from MS store

like with the older 1.5.4 version, the 1.5.7 version also requires an internet connection for actual installation (unless there's a way to install it offline with dism.exe)

MSI recently did release the Realtek 9084 & 9088 drivers that include newer APO3 files (like [this one](https://download.msi.com/dvr_exe/mb/realtek_audio_N_APO3.zip)).
APO3 SWC driver version included is v3.2.2.0.

**Comment by MawaryAgitza** [comment]
Hi, 

First, i want to thank you for this driver. But, i get some trouble here. My Nahimic doesn't change any sound and i can't open nahimic companion, the warning say " Your audio driver is not up to date or your system is not compatible".

Additional info: Windows 10 21H1, my laptop is Acer Aspire 3 A315-41

Here is some screenshot,
![image](https://user-images.githubusercontent.com/81674224/113103369-66be6400-9229-11eb-9e90-c6a5427229d5.png)
![image](https://user-images.githubusercontent.com/81674224/113103414-7473e980-9229-11eb-82bb-9aa4b1006950.png)
![image](https://user-images.githubusercontent.com/81674224/113108250-fc102700-922e-11eb-96a0-24ddb6036538.png)

**Comment by solidus1983** [comment]
> Acer Aspire 3 A315-41

More then likely your device ID's are not in the inf files more so in the nahimic 3 inf files.
